name: npm Package Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: bahmutov/npm-install@v1
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
